project:
  type: website
  output-dir: docs

website:
  title: "Watchash"
  favicon: media/logo.png
  navbar:
    title: false
    logo: media/logo.png
    right:
      - href: index.qmd
        text: Home
#      - about.qmd
      - href: posts.qmd
        text: Posts
      - icon: github 
        href: https://github.com/watchash
        target: _blank
        
  page-footer:
    background: dark
    left: "© 2025 Ian DENG"
    right: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: 
      - sandstone
      - styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full

editor: visual

