project:
  type: website
  output-dir: docs

website:
  title: "Watchash"
  navbar:
    title: false
    logo: media/logo.png
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full

editor: visual

